export const FETCH_DATA = 'template/FETCH_DATA';
export const FETCH_DATA_SUCCESS = 'template/FETCH_DATA_SUCCESS';
export const FETCH_DATA_ERROR = 'template/FETCH_DATA_ERROR';
export const INCREMENT_COUNTER = 'template/INCREMENT_COUNTER';
export const INCREMENT_COUNTER_SUCCESS = 'template/INCREMENT_COUNTER_SUCCESS';
export const INCREMENT_COUNTER_ERROR = 'template/INCREMENT_COUNTER_ERROR';


export const SOCKET_CONNECT = 'template/SOCKET_CONNECT'; 
export const SOCKET_CONNECT_SUCCESS = 'template/SOCKET_CONNECT_SUCCESS'; 
export const SOCKET_CONNECT_ERROR = 'template/SOCKET_CONNECT_ERROR'; 

export const SOCKET_DISCONNECT = 'template/SOCKET_DISCONNECT'; 
export const SOCKET_DISCONNECT_SUCCESS = 'template/SOCKET_DISCONNECT_SUCCESS'; 
export const SOCKET_DISCONNECT_ERROR = 'template/SOCKET_DISCONNECT_ERROR'; 

export const SOCKET_SEND_MESSAGE = 'template/SOCKET_SEND_MESSAGE'; 
export const SOCKET_SEND_MESSAGE_SUCCESS = 'template/SOCKET_SEND_MESSAGE_SUCCESS'; 
export const SOCKET_SEND_MESSAGE_ERROR = 'template/SOCKET_SEND_MESSAGE_ERROR'; 