version: 2
jobs:
   build:
     docker:
       - image: circleci/node:7
     steps:
       - checkout
       - run: echo "hello000ooo000 world"
       - run: npm install
   build_image:
       <<: *defaults
       steps:
           - checkout

           - setup_remote_docker:
               version: 17.06.0-ce

           - run:
               name: Build Docker Image
               command: |
                   docker build . -t SOMETESTNAME

           - run:
               name: Push Image to ECR
               command: |
                   sudo apt install python-pip python-dev
                   sudo pip install awscli
                   eval $(aws ecr get-login --no-include-email | sed 's|https://||' | sed -e 's/-e none//g')
