export const GET_FIGHTERS = 'GET_FIGHTERS';
export const GET_FIGHTERS_SUCCESS = 'GET_FIGHTERS_SUCCESS';

export const GET_CHAMPIONS = 'GET_CHAMPIONS';
export const GET_CHAMPIONS_SUCCESS = 'GET_CHAMPIONS_SUCCESS';
